# Generated by Django 4.1.2 on 2022-10-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleInteractions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
