# Generated by Django 4.1.2 on 2022-10-05 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleInteractions', '0002_delete_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Methods',
            new_name='Method',
        ),
    ]
